#include "../audio.h" 
//#include <dc/sound.h>
#include <kos.h>
#include <dc/sound/sfxmgr.h>
#include <dc/sound/sound.h>
#include <string.h>

#define MAX_SFX 10

#define CENTER 128

sfxhnd_t sfx[MAX_SFX]; 
int sfx_slct = 0; 
int sfx_volume = 255; 

int bg_volume = 8; 
int bg_slct = 1; //useless

void audio_init()
{
	snd_init(); 
	cdrom_init(); 
}
 
void audio_update()
{

}

void audio_quit()
{
	cdrom_cdda_pause(); 
	cdrom_spin_down(); 
	snd_sfx_unload_all(); 
	snd_shutdown(); 
}

int audio_load_track(char* file)
{
	/*useless as CDDA are generated by mkdcdisk*/
	return bg_slct++; 
}

void audio_play_track(int track, int loop)
{
	int l = (loop!=0)?15:0; 
	cdrom_cdda_play(track, track, l, CDDA_TRACKS);
}

int audio_load_sfx(char* file)
{
	char str[40] = {"/rd/"};
	strcat(str, file); 
	sfx[sfx_slct] = snd_sfx_load(str); 
	return sfx_slct++; 
}

void audio_play_sfx(int track)
{
	snd_sfx_play_chn(0 ,sfx[track], sfx_volume, CENTER);
}
