SAMPLE_NUM	:= 5
SAMPLE_NUM_ID := 005
TITLEID := WTJ002301
TARGET		:= $(GAME_NAME)
GNAME :=$(TARGET)
SOURCES		:= .
			
INCLUDES	:= include

LIBS = -lpng -lz -lvitaGL -lSDL2 -lc -lSceCommonDialog_stub -lm -lSceGxm_stub -lSceDisplay_stub -lSceAudio_stub -lSceMotion_stub \
	-lSceHid_stub -lSceTouch_stub -lSceAudioIn_stub -lSceAppMgr_stub -lmathneon \
	-lvitashark -lSceShaccCg_stub -lSceKernelDmacMgr_stub -lSceCtrl_stub -lSceCtrl_stub -lSceShaccCgExt -ltaihen_stub

CFILES   := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.c))
CPPFILES   := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.cpp))
BINFILES := $(foreach dir,$(DATA), $(wildcard $(dir)/*.bin))
OBJS     := $(addsuffix .o,$(BINFILES)) $(CFILES:.c=.o) $(CPPFILES:.cpp=.o) $(OBJ)

PREFIX  = arm-vita-eabi
CC      = $(PREFIX)-gcc
CXX      = $(PREFIX)-g++
CFLAGS  = -std=c99 -Wl,-q -O2 -ftree-vectorize -D __PSV__=1
CXXFLAGS  = $(CFLAGS) -fno-exceptions -std=gnu++11 -fpermissive
ASFLAGS = $(CFLAGS)

all: $(TARGET).vpk

$(TARGET).vpk: eboot.bin
	vita-mksfoex -s TITLE_ID=$(TITLEID) "$(GNAME)" param.sfo
	vita-pack-vpk -s param.sfo -b eboot.bin -a Assets=Assets $@ \
	--add sce_sys/icon0.png=sce_sys/icon0.png \
	--add sce_sys/livearea/contents/bg.png=sce_sys/livearea/contents/bg.png \
	--add sce_sys/livearea/contents/startup.png=sce_sys/livearea/contents/startup.png \
	--add sce_sys/livearea/contents/template.xml=sce_sys/livearea/contents/template.xml \
	$(PROJECT).vpk

eboot.bin: $(TARGET).velf
	vita-make-fself -s $< eboot.bin	
	
%.velf: %.elf
	vita-elf-create $< $@
	
$(TARGET).elf: $(OBJS)
	$(CC) $(CFLAGS) $^ $(LIBS) -o $@
	
clean:
	@rm -rf *.velf *.elf *.vpk $(OBJS) param.sfo eboot.bin
